```{r}
library(rusmaps) # map
library(ggplot2) # plot
library(sp) # plot
library(jsonlite) # parse json
library(dplyr) # df operations 
library(stringr) # str_wrap
library(lubridate) # time
library(RColorBrewer) # colors

parse_vehicle <- function(vehicle, id) {
    damages <- vehicle$parts
    if (is.character(damages) & length(damages) > 0) {
        damages <- data.frame(
            damage = factor(damages),
            vehicle_id = id
        )
    }

    failures <- vehicle$failures
    if (is.character(failures) & length(failures) > 0) {
        failures <- data.frame(
            failure = factor(str_trunc(failures, 45)),   #срез символов
            vehicle_id = id
        )
    }

    vehicle <- data.frame(
        vehicle_id = id,
        type = as.factor(vehicle$type),
        privod = as.factor(vehicle$privod),
        tyres = as.factor(vehicle$tyres),
        year = vehicle$year,
        accident_id = vehicle$accident_id
    )

    return(list(vehicles = vehicle, damages = damages, failures = failures))
}

parse_accident <- function(accident, id) {
    accident <- fromJSON(accident)
    if (accident$mia == FALSE) return(NULL)

    participants <- accident$participants
    if (is.data.frame(participants)) {
        accident$participants_count <- nrow(participants)
        participants$accident_id <- id
    }

    vehicles <- accident$vehicles
    if (is.data.frame(vehicles)) {
        vehicles$accident_id <- id
    }

    road_drawbacks <- accident$road$drawbacks
    if (is.character(road_drawbacks)) {
        road_drawbacks <- data.frame(
            drawback = factor(road_drawbacks),
            accident_id = id
        )
    }

    accident <- data.frame(
        id = id,
        victims = accident$victims,
        fatalities = accident$fatalities,
        vehicles_count = accident$vehicles_count,
        participants_count = accident$participants_count,
        timestamp = as.POSIXlt(accident$timestamp),
        # mia = accident$mia,
        lat = accident$coordinates$latitude,
        long = accident$coordinates$longitude,
        type = factor(str_wrap(accident$type, 40)),
        light = factor(accident$road$light))

    # print(paste(as.character(id), "accident parsed"))


    return(list(accidents = accident, participants = participants,
        vehicles = vehicles, road_drawbacks = road_drawbacks))
}

# lines <- readLines("R/__tmp__/saferoads/saferoads.jsonl")
# lines <- readLines("saferoads_short.jsonl")
lines <- readLines("saferoads.jsonl")

data <- mapply(parse_accident, lines, 1:length(lines), SIMPLIFY = FALSE)

accidents <- do.call(rbind.data.frame,
    unname(lapply(data, function(line) line$accidents)))
participants <- do.call(rbind.data.frame,
    unname(lapply(data, function(line) line$participants)))
vehicles <- do.call(rbind.data.frame,
    unname(lapply(data, function(line) line$vehicles)))
road_drawbacks <- do.call(rbind.data.frame,
    unname(lapply(data, function(line) line$road_drawbacks)))


# print(str(vehicles))


data <- mapply(parse_vehicle, asplit(vehicles, 1), 1:nrow(vehicles),
    SIMPLIFY = FALSE)

vehicles <- do.call(rbind.data.frame,
    unname(lapply(data, function(line) line$vehicles)))
vehicle_damages <- do.call(rbind.data.frame,
    unname(lapply(data, function(line) line$damages)))
vehicle_failures <- do.call(rbind.data.frame,
    unname(lapply(data, function(line) line$failures)))

participants <- mutate(participants,
    gender = factor(gender),
    type = factor(type),
    birthdate = as.Date(birthdate),
    age = as.integer(time_length(difftime(accidents[accident_id, "timestamp"],
        birthdate), "years")))

vehicles <- mutate(vehicles,
    age = as.integer(format(accidents[accident_id, "timestamp"],
        format = "%Y")) - year)

 




# cards <- read.table(file = "cards_short.tsv", sep = "\t", header = TRUE)
# regions <- read.table(file = "regions.tsv", sep = "\t", header = TRUE)


# print(levels(road_drawbacks$drawback))
# print(levels(vehicles$type))

print(str(accidents))
print(str(participants))
print(str(vehicles))
print(str(vehicle_damages))
print(str(vehicle_failures))
print(str(road_drawbacks))







```

```{r}
plot_russia <- function()
    ggplot() +
        geom_polygon(data = map_data(rus_sub),
            aes(x = long, y = lat, group = group),
            color = "black", fill = "white") +
        coord_fixed(2)



plot_russia() +
    geom_point(data = subset(accidents, lat > 10),
        aes(x = long, y = lat),
        color = "red", alpha = 0.01, size = 1) +
    labs(title = "Аварии")


print(levels(accidents$type))

ggplot() +
    geom_bar(data = accidents,
        aes(type)) +
    labs(title = "Распределение видов аварий",
        x = "Вид аварии", y = "Количество") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

plot_russia() +
    geom_point(data = subset(accidents, lat > 10 & type == "Наезд на животное"),
        aes(x = long, y = lat),
        color = "red", alpha = 0.5, size = 1) +
    labs(title = "Аварии, только наезд на животное")

plot_russia() +
    geom_point(data = subset(accidents, lat > 10 & type == "Наезд на велосипедиста"),
        aes(x = long, y = lat),
        color = "red", alpha = 0.5, size = 1) +
    labs(title = "Аварии, только наезд на велосипедиста")


#plot_russia() +
#    geom_point(data = subset(accidents, lat > 10),
#     aes(x = long, y = lat, color = type),
#        size = 1) +
#    labs(title = "Аварии по видам")
    
#plot_russia() +
#    geom_point(data = subset(accidents, lat > 10 & fatalities > 0.9 * participants_count ),
#        aes(x = long, y = lat),
#        color = "red", alpha = 0.5, size = 1) +
#    labs(title = "Аварии, с высокой смертностью")



ggplot() +
    geom_bar(data = subset(participants, type == "Водитель" & !is.na(gender)),
        aes(gender),
        fill = c("pink", "blue")) +
    labs(title = "Распределение количества водителей по полам",
    x = "Пол", y = "Количество водителей")

ggplot() +
    geom_bar(data = vehicle_damages,
        aes(damage)) +
    labs(title = "Распределение повреждений автомобиля",
        x = "Повреждение", y = "Количество") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

no_vehicle_failures <- c("Технические неисправности отсутствуют", "Не устанавливались")



vehicle_failures_ <- vehicle_failures
levels(vehicle_failures_$failure) <- c("Отсутствуют",
    "Не устанавливались",
    rep("Присутствуют",
        length(levels(vehicle_failures_$failure)) - 2))

ggplot() +
    geom_bar(data = vehicle_failures_,
        aes(failure)) +
    labs(title = "Технических неисправности автомобилей",
        x = "Технические неисправности", y = "Количество") +
    coord_flip()
    # theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

print(levels(vehicle_failures$failure))


ggplot() +
    geom_bar(data = subset(vehicle_failures, !failure %in% no_vehicle_failures),
        aes(failure)) +
    labs(title = "Технических неисправности",
        x = "Вид неисправности", y = "Количество") +
    coord_flip()

print(str(participants %>%
        subset(type == "Водитель" & experience < 90) %>%
        group_by(experience, age) %>%
        count() %>%
        ungroup()))



ggplot() +
    geom_point(data = participants %>%
        subset(type == "Водитель" & experience < 90) %>%
        group_by(experience, age) %>%
        count() %>%
        ungroup(),
        aes(x = age, y = experience, color = log(n)),
        size = 2) +
    scale_colour_gradientn(colours = c("green", "red")) +
    labs(title = "Отношение возраста водителя к опыту",
    x = "Возраст", y = "Опыт")

ggplot() +
    geom_histogram(data = subset(participants,
        type == "Водитель" & experience < 90),
        aes(x = experience),
        color = "black", fill = "white") +
    labs(title = "Частота попадания в аварии в зависимости от опыта",
    x = "Опыт", y = "Количество")

ggplot() +
    geom_histogram(data = vehicles,
        aes(x = age),
        color = "black", fill = "white") +
    labs(title = "Частота попадания в аварии в зависимости от возраста автомобиля",
    x = "Возраст авто", y = "Количество")

ggplot() +
    geom_line(data = accidents %>%
        mutate(timestamp = weekdays(timestamp)) %>%
        group_by(timestamp) %>%
        count() %>%
        ungroup(),
        aes(x = timestamp, y = n, group = 1)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(title = "Зависимость кол-ва аварий от дня недели",
    x = "Дата", y = "Количество аварий")

ggplot() +
    geom_line(data = accidents %>%
        mutate(timestamp = format(timestamp, format = "%Y-%m")) %>%
        group_by(timestamp) %>%
        count() %>%
        ungroup(),
        aes(x = timestamp, y = n, group = 1)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(title = "Зависимость кол-ва аварий от времени",
    x = "Дата", y = "Количество аварий")

#ggplot() +
#    geom_line(data = accidents %>%
#        mutate(timestamp = format(timestamp, format = "%m-%d")) %>%
#        group_by(timestamp) %>%
#        count() %>%
#        ungroup(),
#        aes(x = timestamp, y = n, group = 1)) +
#    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
#    labs(title = "Зависимость кол-ва аварий от даты без года",
#    x = "Дата", y = "Количество аварий")

# print(str(accidents %>%
#         mutate(timestamp = format(timestamp, format = "%R")) %>%
#         group_by(timestamp) %>%
#         count() %>%
#         ungroup()))

ggplot() +
    geom_line(data = accidents %>%
        mutate(timestamp = format(timestamp, format = "%H")) %>%
        group_by(timestamp) %>%
        count() %>%
        ungroup(),
        aes(x = timestamp, y = n, group = 1)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(title = "Зависимость кол-ва аварий от времени",
    x = "Время", y = "Количество аварий")


ggplot(data = accidents %>%
    group_by(type) %>%
    summarise_at(c("victims", "fatalities", "participants_count", "vehicles_count"), sum, na.rm = TRUE) %>%
    ungroup()) +
    geom_line(aes(x = type, y = victims / participants_count, group = 1),
        color = "orange") +
    geom_line(aes(x = type, y = fatalities / participants_count, group = 1),
        color = "red") +
    labs(title = "Доля жертв и смертей по видам аварий",
        x = "Вид аварии", y = "Количество") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))



```

```{r}

```